version: '3.8'
services:
    app:
        build: .
        environment:
            DB_URI: mongodb://mongo:27017
            MONGO_USER: ${MONGO_USER}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
            VALIDATOR_PUB_KEY: ${VALIDATOR_PUB_KEY}
            VALIDATOR_ID: ${VALIDATOR_ID}
            START_EPOCH: ${START_EPOCH}
        depends_on:
            - mongo
        volumes:
            - .:/app
            - /app/node_modules # This volume is for caching node modules
    mongo:
        image: mongo:latest
        ports:
            - '27018:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        volumes:
            - mongodb_data:/data/db
volumes:
    mongodb_data:
